"""Add unique constraint to progress

Revision ID: dc32d17d6179
Revises: 5ec7c3108f87
Create Date: 2026-01-22 22:16:39.461627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc32d17d6179'
down_revision: Union[str, Sequence[str], None] = '5ec7c3108f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_flashcard', 'progress', ['user_id', 'flashcard_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_flashcard', 'progress', type_='unique')
    # ### end Alembic commands ###
