import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Image from 'next/image';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavBar()
{
  return (
		<nav className="relative bg-gray-800/50 after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:h-px after:bg-white/10">
			<div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
				<div className="relative flex h-16 items-center justify-between">
					<div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
						<Link href="/" className="text-xl font-bold text-gray-800">
							<Image
                src="/favicon.ico"
                width={32}
                height={32}
                className="hidden md:block"
                alt="App icon"
              />
						</Link>
					</div>
					<div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            <div className="flex space-x-4">
              <Link href="/myflashky" className="rounded-md px-3 py-2 text-sm font-medium text-gray-400 hover:text-white">
                My Flashky
              </Link>
              <Link href="/mydecks" className="rounded-md px-3 py-2 text-sm font-medium text-gray-400 hover:text-white">
                My Decks
              </Link>
              <Link href="/profile" className="rounded-md px-3 py-2 text-sm font-medium text-gray-400 hover:text-white">
                Profile
              </Link>
            </div>
					</div>
				</div>
			</div>
		</nav>
	);
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
