services:
    backend:
        image: flashky-backend:dev
        container_name: backend_dev
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./backend/src:/src/
        env_file:
            - ./.env.dev
        depends_on:
            db:
                condition: service_healthy
    frontend:
        image: flashky-frontend:dev
        container_name: frontend_dev
        build:
            context: .
            dockerfile: frontend/Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
            - /app/node_modules
    db:
        image: postgres:16
        container_name: database_dev
        restart: always
        env_file:
            - ./.env.dev
        ports:
            - "5432:5432"
        volumes:
            - postgres_data_dev:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U flashky_user -d flashky_dev"]
            interval: 5s
            timeout: 3s
            retries: 5
volumes:
    postgres_data_dev:
