services:
    api: 
        build: 
            context: .
            dockerfile: backend/Dockerfile
        command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - "8000:80"
        volumes:
            - ./backend/src:/src/
        environment:
            - ENV=dev