services:
    api: 
        build: 
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./backend/src:/src/
        environment:
            - ENV=dev
    front:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING_INTERVAL="1000"