services:
    api: 
        build: 
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./backend/src:/src/
    front:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
            - /app/node_modules