services:
    api: 
        build: 
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./backend/src:/src/
        environment:
            - ENV=dev